/**
 * Módulo de sanitização centralizado para prevenção de XSS no frontend.
 * Todas as funções utilizam validação por allowlist estrita.
 */

// Protocolo/pattern allowlist para URLs — qualquer coisa fora disso é bloqueada
const SAFE_RELATIVE_PATH = /^\/[a-zA-Z0-9_\-./]+$/;
const SAFE_FILENAME_CHARS = /^[a-zA-Z0-9_\-. ]+$/;

/**
 * Valida uma URL de imagem contra uma allowlist estrita.
 * Aceita APENAS URLs relativas que apontem para /uploads/ ou blob: URLs.
 * Retorna string vazia para qualquer input inválido.
 */
export function sanitizeImageSrc(url: string | null | undefined): string {
  if (!url || typeof url !== "string") return "";
  const trimmed = url.trim();
  
  // Bloquear qualquer tentativa de injeção de protocolo
  if (trimmed.includes("javascript:") || trimmed.includes("data:") || trimmed.includes("vbscript:")) {
    return "";
  }

  // Permitir apenas caminhos relativos seguros (/uploads/...)
  if (SAFE_RELATIVE_PATH.test(trimmed)) {
    return trimmed;
  }
  
  // Permitir blob: URLs (geradas por URL.createObjectURL, 100% seguras)
  if (trimmed.startsWith("blob:")) {
    return trimmed;
  }
  
  return "";
}

/**
 * Alias para retrocompatibilidade.
 * @deprecated Use sanitizeImageSrc para imagens e sanitizeDownloadFilename para downloads.
 */
export function sanitizeUrl(url: string | null | undefined): string {
  return sanitizeImageSrc(url);
}

/**
 * Sanitiza texto para inserção segura em contextos DOM.
 * Remove tags HTML e atributos potencialmente perigosos.
 */
export function sanitizeText(text: string | null | undefined): string {
  if (!text) return "";
  if (typeof window !== "undefined" && (window as any).DOMPurify) {
    return (window as any).DOMPurify.sanitize(text);
  }
  return text
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#x27;");
}

/**
 * Sanitiza o nome de um arquivo para download.
 * Remove todos os caracteres que não sejam alfanuméricos, underscores, hifens, pontos ou espaços.
 */
export function sanitizeDownloadFilename(filename: string): string {
  if (!filename || typeof filename !== "string") return "download";
  const sanitized = filename.replaceAll(/[^a-zA-Z0-9_\-. ]/g, "_");
  return SAFE_FILENAME_CHARS.test(sanitized) ? sanitized : "download";
}

/**
 * Cria um link de download seguro para blobs.
 * O blob URL é gerado pelo browser (URL.createObjectURL) e portanto é intrinsecamente seguro.
 * O filename é sanitizado contra injeção de caracteres especiais.
 */
export function triggerSafeDownload(blob: Blob, filename: string): void {
  // URL.createObjectURL gera uma URL blob: segura e controlada pelo browser
  const safeUrl: string = URL.createObjectURL(blob);
  const safeFilename: string = sanitizeDownloadFilename(filename);
  
  const a: HTMLAnchorElement = document.createElement("a");
  // deepcode ignore DOMXSS: URL is a blob URL generated by the browser, safe from XSS
  a.href = safeUrl;
  a.download = safeFilename;
  a.click();
  // Cleanup imediato
  setTimeout(() => {
    URL.revokeObjectURL(safeUrl);
  }, 100);
}
